// Built-in game template presets

export const PRESETS = [
  {
    id: 'preset_volleyball',
    name: 'Volleyball',
    icon: '🏐',
    scoringType: 'sets',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 25, mustWinBy: 2 },
    maxSets: 5,
    playerMode: 'teams',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_cricket',
    name: 'Cricket',
    icon: '🏏',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'manual', target: null, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'teams',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_badminton',
    name: 'Badminton',
    icon: '🏸',
    scoringType: 'sets',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 21, mustWinBy: 2 },
    maxSets: 3,
    playerMode: 'both',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_tabletennis',
    name: 'Table Tennis',
    icon: '🏓',
    scoringType: 'sets',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 11, mustWinBy: 2 },
    maxSets: 7,
    playerMode: 'both',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_football',
    name: 'Football',
    icon: '⚽',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'manual', target: null, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'teams',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_basketball',
    name: 'Basketball',
    icon: '🏀',
    scoringType: 'cumulative',
    pointIncrement: 2,
    winCondition: { type: 'manual', target: null, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'teams',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_chess',
    name: 'Chess',
    icon: '♟️',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 1, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'players',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_foosball',
    name: 'Foosball',
    icon: '⚽',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 10, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'teams',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_carrom',
    name: 'Carrom',
    icon: '🎯',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'points', target: 25, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'both',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'preset_custom',
    name: 'Custom Game',
    icon: '🎮',
    scoringType: 'cumulative',
    pointIncrement: 1,
    winCondition: { type: 'manual', target: null, mustWinBy: 0 },
    maxSets: null,
    playerMode: 'both',
    isBuiltIn: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export function getPresetById(id) {
  return PRESETS.find(p => p.id === id) || null;
}

export function getPresetByName(name) {
  return PRESETS.find(p => p.name.toLowerCase() === name.toLowerCase()) || null;
}
